name: Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
